### ISSUE TITLE
Aether farmland cannot be trampled / is difficult to trample by jumping/landing on it

### ISSUE THREAD

**Issue by MBatt1** [kalucky0/The-Aether#12]

**Comment by CDAGaming** [comment]
@MBatt1 Will need a video or gif on this one, as it worked fine when testing last night

**Comment by MBatt1** [comment]
https://streamable.com/kk7vxh
The farmland will convert if a block is placed above it or it "drys out" naturally, however that crashes the game.

**Comment by CDAGaming** [comment]
Should be fixed, regression caused it.
